import React from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

import './toplist.css'

const TopList = function({lista, iconType}){
  console.log(lista);

  let icao = {
    "ESGI":	"Alingsås",
    "ESGC":	"Ålleberg",
    "ESMU":	"Älmhult",
    "ESUV":	"Älvsbyn",
    "ESUA":	"Åmsele",
    "ESMP":	"Anderstorp",
    "ESUJ":	"Ånge",
    "ESTA":	"Ängelholm",
    "ESQO":	"Arboga",
    "ESUB":	"Arbrå",
    "ESSA":	"Arlanda",
    "ESNX":	"Arvidsjaur",
    "ESKV":	"Arvika",
    "ESUS":	"Åsele",
    "ESVA":	"Avesta",
    "ESKX":	"Björkvik",
    "ESPJ":	"Boden",
    "ESPG":	"Boden Heli.",
    "ESGE":	"Borås",
    "ESMB":	"Borgholm",
    "ESSD":	"Borlänge",
    "ESSM": "Brattforsheden",
    "ESSB": "Bromma",
    "ESVB": "Bunge",
    "ESFY": "Byholma",
    "ESKD": "Dala-Järna",
    "ESUY": "Edsbyn",
    "ESSC": "Ekeby",
    "ESKH": "Ekshärad",
    "ESMC": "Eksjö-Ränneslätt",
    "ESMA": "Emmaboda",
    "ESME": "Eslöv",
    "ESMF": "Fagerhult",
    "ESGK": "Falköping",
    "ESUF": "Fällfors",
    "ESNF": "Färila",
    "ESMG": "Feringe",
    "ESTF": "Fjällbacka",
    "ESVG": "Gagnef",
    "ESNG": "Gällivare",
    "ESUG": "Gargnäs",
    "ESSK": "Gävle",
    "ESKA":	"Gimo",
    "ESGP":	"Göteborg",
    "ESGN":	"Götene",
    "ESTG":	"Grönhögen",
    "ESKG":	"Gryttjom",
    "ESOH":	"Hagfors",
    "ESMV":	"Hagshult",
    "ESVH":	"Hällefors",
    "ESMT":	"Halmstad",
    "ESUH":	"Härnösand",
    "ESFA":	"Hässleholm/Bokeberg",
    "ESMD":	"Hässleholm/Vankiva",
    "ESOW":	"Hässlö",
    "ESFH":	"Hasslösa",
    "ESNC":	"Hedlanda",
    "ESUT":	"Hemavan",
    "ESGH":	"Herrljunga",
    "ESNK":	"Höga Kusten",
    "ESMH":	"Höganäs",
    "ESNH":	"Hudiksvall",
    "ESSF":	"Hultsfred",
    "ESUE": "Idre",
    "ESSX": "Johannisbergs",
    "ESNJ": "Jokkmokk",
    "ESGJ": "Jönköping",
    "ESMJ": "Kågeröd",
    "ESMQ": "Kalmar",
    "ESIA": "Karlsborg",
    "ESKK": "Karlskoga",
    "ESOK": "Karlstad",
    "ESVK": "Katrineholm",
    "ESNQ": "Kiruna",
    "ESUK": "Kiruna",
    "ESSU": "Kjula",
    "ESFI": "Knislinge",
    "ESVQ": "Köping",
    "ESFQ": "Kosta",
    "ESMK": "Kristianstad",
    "ESML": "Landskrona",
    "ESGG": "Landvetter",
    "ESVL": "Långtora",
    "ESSH": "Laxå",
    "ESGL":	"Lidköping-Hovby",
    "ESFR":	"Lidköping-Råda",
    "ESSL":	"Linköping-Saab",
    "ESCF":	"Linköping/Malmen",
    "ESTL":	"Ljungbyheds",
    "ESUL":	"Ljusdal",
    "ESSG":	"Ludvika",
    "ESPA":	"Luleå",
    "ESMN":	"Lund-Hasslanda",
    "ESNL":	"Lycksele",
    "ESHM":	"Malmö Heli.",
    "ESVM":	"Malung",
    "ESUI":	"Mellansel",
    "ESFM":	"Moholm",
    "ESKM":	"Mora-Siljan",
    "ESGF":	"Morup",
    "ESKO":	"Munkfors",
    "ESCK":	"Norrköping",
    "ESSP":	"Norrköping",
    "ESSN":	"Norrtälje",
    "ESMZ":	"Ölanda",
    "ESOE":	"Örebro",
    "ESGM":	"Öresten",
    "ESNO":	"Örnsköldsvik",
    "ESNR":	"Orsa-Tallhed",
    "ESMO":	"Oskarshamns",
    "ESNZ":	"Östersund",
    "ESNM":	"Östersund-Optand",
    "ESNE":	"Överkalix",
    "ESUO":	"Oviken",
    "ESUP":	"Pajala",
    "ESNP":	"Piteå",
    "ESUR":	"Ramsele",
    "ESDF":	"Ronneby",
    "ESGU":	"Rörkärr",
    "ESGY":	"Säffle",
    "ESKS":	"Sälen",
    "ESFS":	"Sandvik",
    "ESIB":	"Såtenäs",
    "ESIB":	"Såtenäs",
    "ESNT":	"Sattna",
    "ESVS":	"Siljansnäs",
    "ESFJ":	"Sjöbo-Björka",
    "ESSE":	"Skå-Edeby",
    "ESKN":	"Skavsta",
    "ESNS":	"Skellefteå",
    "ESGR":	"Skövde",
    "ESMY":	"Smålandsstenar",
    "ESUM":	"Söderhamn-Mohed",
    "ESNY":	"Söderhamns",
    "ESTT":	"Söderslätt",
    "ESNB":	"Sollefteå",
    "ESMI":	"Sövde",
    "ESVE":	"Stegeborg",
    "ESUD":	"Storumans",
    "ESOL":	"Storvik",
    "ESKS":	"Strängnäs",
    "ESGS":	"Strömstad",
    "ESNA":	"Strömsund",
    "ESMS":	"Sturup",
    "ESKC":	"Sundbro",
    "ESNN":	"Sundsvall",
    "ESKU":	"Sunne/Holmby",
    "ESND":	"Sveg",
    "ESGD":	"Tidaholm",
    "ESKT":	"Tierps",
    "ESMW":	"Tingsryd",
    "ESTO":	"Tomelilla",
    "ESST":	"Torsby",
    "ESMR":	"Trelleborg",
    "ESGT":	"Trollhättan",
    "ESGA":	"Uddevalla",
    "ESNU":	"Umeå",
    "ESCM":	"Uppsala-Ärna",
    "ESFU":	"Uråsa flygbas",
    "ESSZ":	"Vängsö",
    "ESGV":	"Varberg",
    "ESGO":	"Vårgårda",
    "ESMV":	"Värnamo-Hagshult",
    "ESSW":	"Västerviks",
    "ESMX":	"Växjö",
    "ESPE":	"Vidsel",
    "ESNV":	"Vilhelmina",
    "ESSV":	"Visby",
    "ESSI":	"Visingsö"
  }

  let capitalize = (str)=>{
    return str.charAt(0).toUpperCase() + str.slice(1)
  }



  return (
    <div className="statsCard">
    <div className="icon">
      <FontAwesomeIcon icon={iconType} />
    </div>

    <ol>
    {lista.map((item, index) => (
    <li><span>{(icao[item.destination])?icao[item.destination]:capitalize(item.destination.toLowerCase())}</span><span className="counter"><FontAwesomeIcon className="counterIcon" icon={"plane-departure"} />{item.visits}</span></li>
    ))}
    </ol>

    <div className="cardText">
      <span className="unit">Destinationer</span>
      <i><span className="desc">Top fem besökta</span></i>
    </div>
    </div>
  )
}

export default TopList
